/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is true */
#include<time.h>
#include <pthread.h>

typedef unsigned long size_t;
struct __anonstruct_aes256_context_25 {
   unsigned char key[32] ;
   unsigned char enckey[32] ;
   unsigned char deckey[32] ;
};
typedef struct __anonstruct_aes256_context_25 aes256_context;
#pragma merger("0","/tmp/cil-X0VG6u4D.i","")
void aes256_init(aes256_context *ctx , unsigned char *k ) ;
void aes256_done(aes256_context *ctx ) ;
void aes256_encrypt_ecb(aes256_context *ctx , unsigned char *buf ) ;
void aes256_decrypt_ecb(aes256_context *ctx , unsigned char *buf ) ;
int encrypt(void) 
{ 
  aes256_context ctx ;
  unsigned char key[32] ;
  unsigned char buf[128] ;
  unsigned char i ;

  {
  i = (unsigned char)0;
  while ((unsigned long )i < sizeof(buf)) {
    buf[i] = (unsigned char )((int )i * 16 + (int )i);
    i = (unsigned char )((int )i + 1);
  }
  i = (unsigned char)0;
  while ((unsigned long )i < sizeof(key)) {
    key[i] = i;
    i = (unsigned char )((int )i + 1);
  }
  aes256_init(& ctx, key);
  aes256_encrypt_ecb(& ctx, buf);
  aes256_init(& ctx, key);
  aes256_decrypt_ecb(& ctx, buf);
  aes256_done(& ctx);
  return (0);
}
}
int main(int argc , char **argv ) 
{ 
  size_t i ;

  {
  i = (size_t )0;
  while (i < 1024UL) {
    encrypt();
    i ++;
  }
  return (0);
}
}
#pragma merger("0","/tmp/cil-KPU1r2zf.i","")
unsigned char gf_alog(unsigned char x ) 
{ 
  unsigned char atb ;
  unsigned char z ;
  unsigned char tmp ;

  {
  atb = (unsigned char)1;
  while (1) {
    tmp = x;
    x = (unsigned char )((int )x - 1);
    if (! tmp) {
      break;
    }
    z = atb;
    atb = (unsigned char )((int )atb << 1);
    if ((int )z & 128) {
      atb = (unsigned char )((int )atb ^ 27);
    }
    atb = (unsigned char )((int )atb ^ (int )z);
  }
  return (atb);
}
}
unsigned char gf_log(unsigned char x ) 
{ 
  unsigned char atb ;
  unsigned char i ;
  unsigned char z ;

  {
  atb = (unsigned char)1;
  i = (unsigned char)0;
  while (! ((int )atb == (int )x)) {
    z = atb;
    atb = (unsigned char )((int )atb << 1);
    if ((int )z & 128) {
      atb = (unsigned char )((int )atb ^ 27);
    }
    atb = (unsigned char )((int )atb ^ (int )z);
    i = (unsigned char )((int )i + 1);
    if (! ((int )i > 0)) {
      break;
    }
  }
  return (i);
}
}
unsigned char gf_mulinv(unsigned char x ) 
{ 
  unsigned char tmp ;
  unsigned char tmp___0 ;
  int tmp___1 ;

  {
  if (x) {
    tmp = gf_log(x);
    tmp___0 = gf_alog((unsigned char )(255 - (int )tmp));
    tmp___1 = (int )tmp___0;
  } else {
    tmp___1 = 0;
  }
  return ((unsigned char )tmp___1);
}
}
unsigned char rj_sbox(unsigned char x ) 
{ 
  unsigned char y ;
  unsigned char sb ;

  {
  y = gf_mulinv(x);
  sb = y;
  y = (unsigned char )(((int )y << 1) | ((int )y >> 7));
  sb = (unsigned char )((int )sb ^ (int )y);
  y = (unsigned char )(((int )y << 1) | ((int )y >> 7));
  sb = (unsigned char )((int )sb ^ (int )y);
  y = (unsigned char )(((int )y << 1) | ((int )y >> 7));
  sb = (unsigned char )((int )sb ^ (int )y);
  y = (unsigned char )(((int )y << 1) | ((int )y >> 7));
  sb = (unsigned char )((int )sb ^ (int )y);
  return ((unsigned char )((int )sb ^ 99));
}
}
unsigned char rj_sbox_inv(unsigned char x ) 
{ 
  unsigned char y ;
  unsigned char sb ;
  unsigned char tmp ;

  {
  y = (unsigned char )((int )x ^ 99);
  y = (unsigned char )(((int )y << 1) | ((int )y >> 7));
  sb = y;
  y = (unsigned char )(((int )y << 2) | ((int )y >> 6));
  sb = (unsigned char )((int )sb ^ (int )y);
  y = (unsigned char )(((int )y << 3) | ((int )y >> 5));
  sb = (unsigned char )((int )sb ^ (int )y);
  tmp = gf_mulinv(sb);
  return (tmp);
}
}
unsigned char rj_xtime(unsigned char x ) 
{ 
  int tmp ;

  {
  if ((int )x & 128) {
    tmp = ((int )x << 1) ^ 27;
  } else {
    tmp = (int )x << 1;
  }
  return ((unsigned char )tmp);
}
}
void aes_subBytes(unsigned char *buf ) 
{ 
  register unsigned char i ;
  unsigned char tmp ;

  {
  i = (unsigned char)16;
  while (1) {
    tmp = i;
    i = (unsigned char )((int )i - 1);
    if (! tmp) {
      break;
    }
    *(buf + i) = rj_sbox(*(buf + i));
  }
  return;
}
}
void aes_subBytes_inv(unsigned char *buf ) 
{ 
  register unsigned char i ;
  unsigned char tmp ;

  {
  i = (unsigned char)16;
  while (1) {
    tmp = i;
    i = (unsigned char )((int )i - 1);
    if (! tmp) {
      break;
    }
    *(buf + i) = rj_sbox_inv(*(buf + i));
  }
  return;
}
}
void aes_addRoundKey(unsigned char *buf , unsigned char *key ) 
{ 
  register unsigned char i ;
  unsigned char tmp ;

  {
  i = (unsigned char)16;
  while (1) {
    tmp = i;
    i = (unsigned char )((int )i - 1);
    if (! tmp) {
      break;
    }
    *(buf + i) = (unsigned char )((int )*(buf + i) ^ (int )*(key + i));
  }
  return;
}
}
void aes_addRoundKey_cpy(unsigned char *buf , unsigned char *key , unsigned char *cpk ) 
{ 
  register unsigned char i ;
  unsigned char tmp ;
  unsigned char tmp___0 ;

  {
  i = (unsigned char)16;
  while (1) {
    tmp___0 = i;
    i = (unsigned char )((int )i - 1);
    if (! tmp___0) {
      break;
    }
    tmp = *(key + i);
    *(cpk + i) = tmp;
    *(buf + i) = (unsigned char )((int )*(buf + i) ^ (int )tmp);
    *(cpk + (16 + (int )i)) = *(key + (16 + (int )i));
  }
  return;
}
}
void aes_shiftRows(unsigned char *buf ) 
{ 
  register unsigned char i ;
  register unsigned char j ;

  {
  i = *(buf + 1);
  *(buf + 1) = *(buf + 5);
  *(buf + 5) = *(buf + 9);
  *(buf + 9) = *(buf + 13);
  *(buf + 13) = i;
  i = *(buf + 10);
  *(buf + 10) = *(buf + 2);
  *(buf + 2) = i;
  j = *(buf + 3);
  *(buf + 3) = *(buf + 15);
  *(buf + 15) = *(buf + 11);
  *(buf + 11) = *(buf + 7);
  *(buf + 7) = j;
  j = *(buf + 14);
  *(buf + 14) = *(buf + 6);
  *(buf + 6) = j;
  return;
}
}
void aes_shiftRows_inv(unsigned char *buf ) 
{ 
  register unsigned char i ;
  register unsigned char j ;

  {
  i = *(buf + 1);
  *(buf + 1) = *(buf + 13);
  *(buf + 13) = *(buf + 9);
  *(buf + 9) = *(buf + 5);
  *(buf + 5) = i;
  i = *(buf + 2);
  *(buf + 2) = *(buf + 10);
  *(buf + 10) = i;
  j = *(buf + 3);
  *(buf + 3) = *(buf + 7);
  *(buf + 7) = *(buf + 11);
  *(buf + 11) = *(buf + 15);
  *(buf + 15) = j;
  j = *(buf + 6);
  *(buf + 6) = *(buf + 14);
  *(buf + 14) = j;
  return;
}
}
void aes_mixColumns(unsigned char *buf ) 
{ 
  register unsigned char i ;
  register unsigned char a ;
  register unsigned char b ;
  register unsigned char c ;
  register unsigned char d ;
  register unsigned char e ;
  unsigned char tmp ;
  unsigned char tmp___0 ;
  unsigned char tmp___1 ;
  unsigned char tmp___2 ;

  {
  i = (unsigned char)0;
  while ((int )i < 16) {
    a = *(buf + i);
    b = *(buf + ((int )i + 1));
    c = *(buf + ((int )i + 2));
    d = *(buf + ((int )i + 3));
    e = (unsigned char )((((int )a ^ (int )b) ^ (int )c) ^ (int )d);
    tmp = rj_xtime((unsigned char )((int )a ^ (int )b));
    *(buf + i) = (unsigned char )((int )*(buf + i) ^ ((int )e ^ (int )tmp));
    tmp___0 = rj_xtime((unsigned char )((int )b ^ (int )c));
    *(buf + ((int )i + 1)) = (unsigned char )((int )*(buf + ((int )i + 1)) ^ ((int )e ^ (int )tmp___0));
    tmp___1 = rj_xtime((unsigned char )((int )c ^ (int )d));
    *(buf + ((int )i + 2)) = (unsigned char )((int )*(buf + ((int )i + 2)) ^ ((int )e ^ (int )tmp___1));
    tmp___2 = rj_xtime((unsigned char )((int )d ^ (int )a));
    *(buf + ((int )i + 3)) = (unsigned char )((int )*(buf + ((int )i + 3)) ^ ((int )e ^ (int )tmp___2));
    i = (unsigned char )((int )i + 4);
  }
  return;
}
}
void aes_mixColumns_inv(unsigned char *buf ) 
{ 
  register unsigned char i ;
  register unsigned char a ;
  register unsigned char b ;
  register unsigned char c ;
  register unsigned char d ;
  register unsigned char e ;
  register unsigned char x ;
  register unsigned char y ;
  register unsigned char z ;
  unsigned char tmp ;
  unsigned char tmp___0 ;
  unsigned char tmp___1 ;
  unsigned char tmp___2 ;
  unsigned char tmp___3 ;
  unsigned char tmp___4 ;
  unsigned char tmp___5 ;
  unsigned char tmp___6 ;

  {
  i = (unsigned char)0;
  while ((int )i < 16) {
    a = *(buf + i);
    b = *(buf + ((int )i + 1));
    c = *(buf + ((int )i + 2));
    d = *(buf + ((int )i + 3));
    e = (unsigned char )((((int )a ^ (int )b) ^ (int )c) ^ (int )d);
    z = rj_xtime(e);
    tmp = rj_xtime((unsigned char )(((int )z ^ (int )a) ^ (int )c));
    tmp___0 = rj_xtime(tmp);
    x = (unsigned char )((int )e ^ (int )tmp___0);
    tmp___1 = rj_xtime((unsigned char )(((int )z ^ (int )b) ^ (int )d));
    tmp___2 = rj_xtime(tmp___1);
    y = (unsigned char )((int )e ^ (int )tmp___2);
    tmp___3 = rj_xtime((unsigned char )((int )a ^ (int )b));
    *(buf + i) = (unsigned char )((int )*(buf + i) ^ ((int )x ^ (int )tmp___3));
    tmp___4 = rj_xtime((unsigned char )((int )b ^ (int )c));
    *(buf + ((int )i + 1)) = (unsigned char )((int )*(buf + ((int )i + 1)) ^ ((int )y ^ (int )tmp___4));
    tmp___5 = rj_xtime((unsigned char )((int )c ^ (int )d));
    *(buf + ((int )i + 2)) = (unsigned char )((int )*(buf + ((int )i + 2)) ^ ((int )x ^ (int )tmp___5));
    tmp___6 = rj_xtime((unsigned char )((int )d ^ (int )a));
    *(buf + ((int )i + 3)) = (unsigned char )((int )*(buf + ((int )i + 3)) ^ ((int )y ^ (int )tmp___6));
    i = (unsigned char )((int )i + 4);
  }
  return;
}
}
void aes_expandEncKey(unsigned char *k , unsigned char *rc ) 
{ 
  register unsigned char i ;
  unsigned char tmp ;
  unsigned char tmp___0 ;
  unsigned char tmp___1 ;
  unsigned char tmp___2 ;
  unsigned char tmp___3 ;
  unsigned char tmp___4 ;
  unsigned char tmp___5 ;
  unsigned char tmp___6 ;

  {
  tmp = rj_sbox(*(k + 29));
  *(k + 0) = (unsigned char )((int )*(k + 0) ^ ((int )tmp ^ (int )*rc));
  tmp___0 = rj_sbox(*(k + 30));
  *(k + 1) = (unsigned char )((int )*(k + 1) ^ (int )tmp___0);
  tmp___1 = rj_sbox(*(k + 31));
  *(k + 2) = (unsigned char )((int )*(k + 2) ^ (int )tmp___1);
  tmp___2 = rj_sbox(*(k + 28));
  *(k + 3) = (unsigned char )((int )*(k + 3) ^ (int )tmp___2);
  *rc = (unsigned char )(((int )*rc << 1) ^ (((int )*rc >> 7) & 1) * 27);
  i = (unsigned char)4;
  while ((int )i < 16) {
    *(k + i) = (unsigned char )((int )*(k + i) ^ (int )*(k + ((int )i - 4)));
    *(k + ((int )i + 1)) = (unsigned char )((int )*(k + ((int )i + 1)) ^ (int )*(k + ((int )i - 3)));
    *(k + ((int )i + 2)) = (unsigned char )((int )*(k + ((int )i + 2)) ^ (int )*(k + ((int )i - 2)));
    *(k + ((int )i + 3)) = (unsigned char )((int )*(k + ((int )i + 3)) ^ (int )*(k + ((int )i - 1)));
    i = (unsigned char )((int )i + 4);
  }
  tmp___3 = rj_sbox(*(k + 12));
  *(k + 16) = (unsigned char )((int )*(k + 16) ^ (int )tmp___3);
  tmp___4 = rj_sbox(*(k + 13));
  *(k + 17) = (unsigned char )((int )*(k + 17) ^ (int )tmp___4);
  tmp___5 = rj_sbox(*(k + 14));
  *(k + 18) = (unsigned char )((int )*(k + 18) ^ (int )tmp___5);
  tmp___6 = rj_sbox(*(k + 15));
  *(k + 19) = (unsigned char )((int )*(k + 19) ^ (int )tmp___6);
  i = (unsigned char)20;
  while ((int )i < 32) {
    *(k + i) = (unsigned char )((int )*(k + i) ^ (int )*(k + ((int )i - 4)));
    *(k + ((int )i + 1)) = (unsigned char )((int )*(k + ((int )i + 1)) ^ (int )*(k + ((int )i - 3)));
    *(k + ((int )i + 2)) = (unsigned char )((int )*(k + ((int )i + 2)) ^ (int )*(k + ((int )i - 2)));
    *(k + ((int )i + 3)) = (unsigned char )((int )*(k + ((int )i + 3)) ^ (int )*(k + ((int )i - 1)));
    i = (unsigned char )((int )i + 4);
  }
  return;
}
}
void aes_expandDecKey(unsigned char *k , unsigned char *rc ) 
{ 
  unsigned char i ;
  unsigned char tmp ;
  unsigned char tmp___0 ;
  unsigned char tmp___1 ;
  unsigned char tmp___2 ;
  int tmp___3 ;
  unsigned char tmp___4 ;
  unsigned char tmp___5 ;
  unsigned char tmp___6 ;
  unsigned char tmp___7 ;

  {
  i = (unsigned char)28;
  while ((int )i > 16) {
    *(k + (int )i) = (unsigned char )((int )*(k + (int )i) ^ (int )*(k + ((int )i - 4)));
    *(k + ((int )i + 1)) = (unsigned char )((int )*(k + ((int )i + 1)) ^ (int )*(k + ((int )i - 3)));
    *(k + ((int )i + 2)) = (unsigned char )((int )*(k + ((int )i + 2)) ^ (int )*(k + ((int )i - 2)));
    *(k + ((int )i + 3)) = (unsigned char )((int )*(k + ((int )i + 3)) ^ (int )*(k + ((int )i - 1)));
    i = (unsigned char )((int )i - 4);
  }
  tmp = rj_sbox(*(k + 12));
  *(k + 16) = (unsigned char )((int )*(k + 16) ^ (int )tmp);
  tmp___0 = rj_sbox(*(k + 13));
  *(k + 17) = (unsigned char )((int )*(k + 17) ^ (int )tmp___0);
  tmp___1 = rj_sbox(*(k + 14));
  *(k + 18) = (unsigned char )((int )*(k + 18) ^ (int )tmp___1);
  tmp___2 = rj_sbox(*(k + 15));
  *(k + 19) = (unsigned char )((int )*(k + 19) ^ (int )tmp___2);
  i = (unsigned char)12;
  while ((int )i > 0) {
    *(k + (int )i) = (unsigned char )((int )*(k + (int )i) ^ (int )*(k + ((int )i - 4)));
    *(k + ((int )i + 1)) = (unsigned char )((int )*(k + ((int )i + 1)) ^ (int )*(k + ((int )i - 3)));
    *(k + ((int )i + 2)) = (unsigned char )((int )*(k + ((int )i + 2)) ^ (int )*(k + ((int )i - 2)));
    *(k + ((int )i + 3)) = (unsigned char )((int )*(k + ((int )i + 3)) ^ (int )*(k + ((int )i - 1)));
    i = (unsigned char )((int )i - 4);
  }
  if ((int )*rc & 1) {
    tmp___3 = 141;
  } else {
    tmp___3 = 0;
  }
  *rc = (unsigned char )(((int )*rc >> 1) ^ tmp___3);
  tmp___4 = rj_sbox(*(k + 29));
  *(k + 0) = (unsigned char )((int )*(k + 0) ^ ((int )tmp___4 ^ (int )*rc));
  tmp___5 = rj_sbox(*(k + 30));
  *(k + 1) = (unsigned char )((int )*(k + 1) ^ (int )tmp___5);
  tmp___6 = rj_sbox(*(k + 31));
  *(k + 2) = (unsigned char )((int )*(k + 2) ^ (int )tmp___6);
  tmp___7 = rj_sbox(*(k + 28));
  *(k + 3) = (unsigned char )((int )*(k + 3) ^ (int )tmp___7);
  return;
}
}
void aes256_init(aes256_context *ctx , unsigned char *k ) 
{ 
  unsigned char rcon ;
  register unsigned char i ;
  unsigned char tmp ;

  {
  rcon = (unsigned char)1;
  i = (unsigned char)0;
  while ((unsigned long )i < sizeof(ctx->key)) {
    tmp = *(k + i);
    ctx->deckey[i] = tmp;
    ctx->enckey[i] = tmp;
    i = (unsigned char )((int )i + 1);
  }
  i = (unsigned char)8;
  while (1) {
    i = (unsigned char )((int )i - 1);
    if (! i) {
      break;
    }
    aes_expandEncKey(ctx->deckey, & rcon);
  }
  return;
}
}
void aes256_done(aes256_context *ctx ) 
{ 
  register unsigned char i ;
  unsigned char tmp ;
  unsigned char tmp___0 ;

  {
  i = (unsigned char)0;
  while ((unsigned long )i < sizeof(ctx->key)) {
    tmp___0 = (unsigned char)0;
    ctx->deckey[i] = tmp___0;
    tmp = tmp___0;
    ctx->enckey[i] = tmp;
    ctx->key[i] = tmp;
    i = (unsigned char )((int )i + 1);
  }
  return;
}
}
void aes256_encrypt_ecb(aes256_context *ctx , unsigned char *buf ) 
{ 
  unsigned char i ;
  unsigned char rcon ;

  {
  aes_addRoundKey_cpy(buf, ctx->enckey, ctx->key);
  i = (unsigned char)1;
  rcon = (unsigned char)1;
  while ((int )i < 14) {
    aes_subBytes(buf);
    aes_shiftRows(buf);
    aes_mixColumns(buf);
    if ((int )i & 1) {
      aes_addRoundKey(buf, & ctx->key[16]);
    } else {
      aes_expandEncKey(ctx->key, & rcon);
      aes_addRoundKey(buf, ctx->key);
    }
    i = (unsigned char )((int )i + 1);
  }
  aes_subBytes(buf);
  aes_shiftRows(buf);
  aes_expandEncKey(ctx->key, & rcon);
  aes_addRoundKey(buf, ctx->key);
  return;
}
}
void aes256_decrypt_ecb(aes256_context *ctx , unsigned char *buf ) 
{ 
  unsigned char i ;
  unsigned char rcon ;

  {
  aes_addRoundKey_cpy(buf, ctx->deckey, ctx->key);
  aes_shiftRows_inv(buf);
  aes_subBytes_inv(buf);
  i = (unsigned char)14;
  rcon = (unsigned char)128;
  while (1) {
    i = (unsigned char )((int )i - 1);
    if (! i) {
      break;
    }
    if ((int )i & 1) {
      aes_expandDecKey(ctx->key, & rcon);
      aes_addRoundKey(buf, & ctx->key[16]);
    } else {
      aes_addRoundKey(buf, ctx->key);
    }
    aes_mixColumns_inv(buf);
    aes_shiftRows_inv(buf);
    aes_subBytes_inv(buf);
  }
  aes_addRoundKey(buf, ctx->key);
  return;
}
}
