all : p1.exe p2.exe p3.exe p4.exe p5.exe p6.exe p7.exe p8.exe p9.exe

p1.exe : p1.o
	gcc -o p1.exe p1.o
p1.o : p1.c
	gcc -c p1.c
p2.exe : p2.o
	gcc -o p2.exe p2.o
p2.o : p2.c
	gcc -c p2.c
p3.exe : p3.o
	gcc -o p3.exe p3.o
p3.o : p3.c
	gcc -c p3.c
p4.exe : p4.o
	gcc -o p4.exe p4.o
p4.o : p4.c
	gcc -c p4.c
p5.exe : p5.o
	gcc -o p5.exe p5.o
p5.o : p5.c
	gcc -c p5.c
p6.exe : p6.o
	gcc -o p6.exe p6.o
p6.o : p6.c
	gcc -c p6.c
p7.exe : p7.o
	gcc -o p7.exe p7.o
p7.o : p7.c
	gcc -c p7.c
p8.exe : p8.o
	gcc -o p8.exe p8.o
p8.o : p8.c
	gcc -c p8.c
p9.exe : p9.o
	gcc -o p9.exe p9.o
p9.o : p9.c
	gcc -c p9.c

clean :
	rm p1.o p2.o p3.o p4.o p5.o p6.o p7.o p8.o p9.o p1.exe p2.exe p3.exe p4.exe p5.exe p6.exe p7.exe p8.exe p9.exe


