/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */
#include <stdio.h>

struct struct145;
struct struct77;
struct struct77 {
   struct struct77 *var78 ;
   unsigned long var80 ;
};
unsigned long longArray[2] ;
extern void exit(int status) ; 
struct struct77 *var106[2] ;
extern void *malloc(unsigned long size) ;
struct struct145 {
   unsigned long var146 ;
   struct struct145 *var148 ;
};
void computation(unsigned long *inp , unsigned long *out ) 
{ 
  unsigned long arrayOne[2] ;
  struct struct145 *varImp[2] ;
  struct struct145 *varZero ;
  struct struct145 *varOne ;
  struct struct145 *varTwo ;
  struct struct145 *varThree ;
  struct struct77 *varFour ; 
  struct struct77 *varFive ;
  struct struct77 *varSix ; 
  struct struct77 *varSeven ;
  char charOne ;
  unsigned int calcVar ;
  unsigned int incr ;
  register unsigned long manipulateVar ;
  unsigned long changeVar ;
  unsigned long compareVar ;
    varImp[0] = (struct struct145 *)0;
    varImp[1] = (struct struct145 *)0;
    arrayOne[0] = *(inp) + 395318398;
    arrayOne[1] = (*(inp) * arrayOne[0] >> 15) | (*(inp) * arrayOne[0] << 49);
    longArray[0] = *(inp) | (903700589 - arrayOne[1]); 
    longArray[1] = *(inp) << 1; 
    varZero = (struct struct145 *)malloc(24);
    varZero->var148 = varZero;
    varImp[0] = varZero;
    varZero->var146 = 0; 
    varOne = (struct struct145 *)malloc(24);
    varOne->var146 = ((*(inp) + 996783958) << ((((arrayOne[1] + 446531527) >> 1) & 15) | 1)) | ((*(inp) + 996783958) >> (64 - ((((arrayOne[1] + 446531527) >> 1) & 15) | 1)));
    varOne->var148 = (varImp[0])->var148;
    (varImp[0])->var148 = varOne;
    varImp[0] = (varImp[0])->var148;
    varTwo = (struct struct145 *)malloc(24);
    varTwo->var148 = varTwo;
    varImp[1] = varTwo;
    varTwo->var146 = 0;
    varThree = (struct struct145 *)malloc(24);
    varThree->var146 = (*(inp) - arrayOne[0]) & ((arrayOne[1] << ((((1020250812 | longArray[0]) >> 4) & 15) | 1)) | (arrayOne[1] >> (64 - ((((1020250812 | longArray[0]) >> 4) & 15) | 1)))); 
    varThree->var148 = (varImp[1])->var148;
    (varImp[1])->var148 = varThree;
    varImp[1] = (varImp[1])->var148;
    varFour = (struct struct77 *)malloc(24);
    varFour->var78 = varFour;
    var106[0] = varFour; 
    varFour->var80 = 0; 
    varFive = (struct struct77 *)malloc(24);
    varFive->var80 = (*(inp) - arrayOne[1]) + (longArray[0] + longArray[1]); 
    varFive->var78 = (var106[0])->var78; 
    (var106[0])->var78 = varFive; 
    var106[0] = (var106[0])->var78; 
    varSix = (struct struct77 *)malloc(24);
    varSix->var78 = varSix;
    var106[1] = varSix; 
    varSix->var80 = 0; 
    varSeven = (struct struct77 *)malloc(24);
    varSeven->var80 = (*(inp) >> ((longArray[1] & 7) | 1)) - 437752715 * (227931849 & arrayOne[1]); 
    varSeven->var78 = (var106[1])->var78; 
    (var106[1])->var78 = varSeven; 
    var106[1] = (var106[1])->var78; 
    __asm__  volatile   ("cmpl %[right], %[left]\n;\t"
                         "pushf\n;\t"
                         "popq %[tmp26]\n;\t": [tmp26] "=r" (manipulateVar): [left] "r" (! ((arrayOne[1] >> 1) & 1)),
                         [right] "r" (0));
    changeVar = ~ ((manipulateVar >> 6) & 1) & 1;
    compareVar = ~ changeVar & 1;
    if(compareVar * 2 == 0 ){
      (varImp[(longArray[0]) % 2])->var146 = (arrayOne[0] >> (((arrayOne[((var106[0])->var80) % 2] >> 3) & 15) | 1)) | (arrayOne[0] << (64 - (((arrayOne[((var106[0])->var80) % 2] >> 3) & 15) | 1)));     
      charOne = *((char *)(& (varImp[1])->var146) + 3); 
      *((char *)(& (varImp[1])->var146) + 3) = *((char *)(& (varImp[1])->var146) + 6); 
      *((char *)(& (varImp[1])->var146) + 6) = charOne; 
      charOne = *((char *)(& (varImp[1])->var146) + 2); 
      *((char *)(& (varImp[1])->var146) + 2) = *((char *)(& (varImp[1])->var146) + 3); 
      *((char *)(& (varImp[1])->var146) + 3) = charOne; 
      (var106[((var106[1])->var80) % 2])->var80 = arrayOne[1]; 
    } 
    calcVar = 0;
    for(incr=0;incr < 1; incr=incr+2){
      longArray[1] = arrayOne[0] << (((longArray[incr] >> 2) & 7) | 1); 
      (varImp[calcVar % 2])->var146 = arrayOne[((varImp[1])->var146) % 2]; 
      var106[((var106[1])->var80) % 2] = (var106[((var106[1])->var80) % 2])->var78;         
      calcVar = ((calcVar + 1) % 2);
    }
    *(out) = (arrayOne[0] + arrayOne[1]) * ((varImp[0])->var146 + (varImp[1])->var146) >> (((((longArray[0] + longArray[1]) << ((((var106[0])->var80 + (var106[1])->var80) & 7) | 1)) >> 2) & 7) | 1);
    return;
}
int main(int argc, char *argv[]) 
{ 
  unsigned long inp;
  unsigned long out;
  if (argc != 2) {
    printf("Call this program with %i arguments\n", 1);
    exit(-1);
  }
  inp  = strtoul(argv[1], (char const   *)0, 10);
  computation(&inp, &out);
  printf("%lu\n", out);
  return (0);
}

