/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct t___145;
struct t___77;
struct t___8;
struct t___85;
struct t___107;
union t___110;
union t___113;
union t___124;
union t___82;
union t___128;
union t___88;
struct t___116;
struct t___93;
struct t___97;
union t___135;
struct t___71;
struct t___139;
extern int gettimeofday(struct t___139 *tv , void *tz ) ;
int o___64  =    0;
extern int pthread_cond_broadcast(union t___124 *cond ) ;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned long alignment , unsigned long size ) ;
void o___65(void) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
typedef union t___135 o___66;
extern unsigned long strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
typedef union t___128 o___67;
typedef union t___88 o___68;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) pthread_mutex_init)(o___67 *__mutex ,
                                                                                                         o___68 const   *__mutexattr ) ;
typedef long o___69;
typedef long o___70;
struct t___71 {
   o___70 f___72 ;
   o___69 f___73 ;
};
extern int printf(char const   *format  , ...) ;
char **o___74  =    (char **)0;
extern int pthread_cond_signal(union t___124 *cond ) ;
char **o___75  =    (char **)0;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
extern int unlink(char const   *filename ) ;
void o___76(unsigned long *l___1074 , unsigned long *l___1075 ) ;
struct t___77 {
   struct t___77 *f___78 ;
   struct t___77 *f___79 ;
   unsigned long f___80 ;
};
unsigned long o___81[2] ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(union t___128 *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
union t___82 {
   char f___83[4] ;
   int f___84 ;
};
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned long namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
struct t___85 {
   unsigned int f___86 ;
   unsigned int f___87 ;
};
union t___88 {
   char f___89[4] ;
   int f___90 ;
};
extern int fprintf(struct t___8 *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
struct t___77 *o___91[2] ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
int main(int l___1062 , char **l___1063 , char **l___1064 ) ;
typedef struct t___8 o___92;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned long len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
struct t___93 {
   struct t___93 *f___94 ;
   struct t___93 *f___95 ;
};
typedef struct t___93 o___96;
struct t___97 {
   int f___98 ;
   unsigned int f___99 ;
   int f___100 ;
   unsigned int f___101 ;
   int f___102 ;
   short f___103 ;
   short f___104 ;
   o___96 f___105 ;
};
struct t___77 *o___106[2] ;
struct t___107 {
   unsigned int f___108 ;
   unsigned int f___109 ;
};
union t___110 {
   unsigned long long f___111 ;
   struct t___107 f___112 ;
};
union t___113 {
   unsigned long long f___114 ;
   struct t___85 f___115 ;
};
struct t___116 {
   union t___110 f___117 ;
   union t___113 f___118 ;
   unsigned int f___119[2] ;
   unsigned int f___120[2] ;
   unsigned int f___121 ;
   unsigned int f___122 ;
   unsigned int f___123[2] ;
};
union t___124 {
   struct t___116 f___125 ;
   char f___126[48] ;
   long long f___127 ;
};
union t___128 {
   struct t___97 f___129 ;
   char f___130[40] ;
   long f___131 ;
};
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(union t___124 *cond , union t___124 *mutex ) ;
extern void perror(char const   *str ) ;
void o___132(void) ;
extern long write(int filedes , void *buf , unsigned long nbyte ) ;
typedef union t___124 o___133;
typedef union t___82 o___134;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) pthread_cond_init)(o___133 * __restrict  __cond ,
                                                                                                        o___134 const   * __restrict  __cond_attr ) ;
union t___135 {
   char f___136[56] ;
   long f___137 ;
};
extern int ptrace(int request , void *pid , void *addr , int data ) ;
void o___138(void) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
struct t___139 {
   long f___140 ;
   long f___141 ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned long nel , unsigned long width , int (*compar)(void *a ,
                                                                                       void *b ) ) ;
extern long time(long *tloc ) ;
void o___142(void) ;
extern int rand() ;
extern long read(int filedes , void *buf , unsigned long nbyte ) ;
typedef unsigned long o___143;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
void o___144(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned long size , char const   *format  , ...) ;
extern void *malloc(unsigned long size ) ;
extern int nanosleep(struct t___71  const  *__requested_time , struct t___71 *__remaining ) ;
struct t___145 {
   unsigned long f___146 ;
   struct t___145 *f___147 ;
   struct t___145 *f___148 ;
};
extern int pthread_mutex_unlock(union t___128 *mutex ) ;
extern int atoi(char const   *s ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,3))) pthread_create)(o___143 * __restrict  __newthread ,
                                                                                             o___66 const   * __restrict  __attr ,
                                                                                             void *(*__start_routine)(void * ) ,
                                                                                             void * __restrict  __arg ) ;
void o___149(void) ;
void o___150(void) ;
extern int fseek(struct t___8 *stream , long offs , int whence ) ;
extern int fscanf(struct t___8 *stream , char const   *format  , ...) ;
void o___151(void) ;
void o___151(void) 
{ 


  {
  o___142();
  o___144();
  o___150();
  return;
}
}
void o___132(void) 
{ 


  {

}
}
void o___76(unsigned long *l___1074 , unsigned long *l___1075 ) 
{ 
  unsigned long l___1077[2] ;
  struct t___145 *l___1078[2] ;
  struct t___145 *l___1079[2] ;
  struct t___145 *l___1080 ;
  struct t___145 *l___1081 ;
  struct t___145 *l___1082 ;
  struct t___145 *l___1083 ;
  struct t___77 *l___1084 ;
  struct t___77 *l___1085 ;
  struct t___77 *l___1086 ;
  struct t___77 *l___1087 ;
  char l___1088 ;
  unsigned int l___1089 ;
  unsigned int l___1090 ;
  void *l___1091 ;
  void *l___1092 ;
  void *l___1093 ;
  void *l___1094 ;
  void *l___1095 ;
  void *l___1096 ;
  void *l___1097 ;
  void *l___1098 ;
  unsigned long l___1099 ;
  register unsigned long l___1100 ;
  unsigned long l___1101 ;
  unsigned long l___1102 ;

  {
  {
  l___1099 = 3;
  }
  while (1) {
    switch (l___1099) {
    case 0: 
    (l___1079[(unsigned long )((int )o___81[0UL]) % 2UL])->f___146 = (l___1077[0UL] >> (((l___1077[(unsigned long )((int )(o___106[0UL])->f___80) % 2UL] >> 3UL) & 15UL) | 1UL)) | (l___1077[0UL] << (64UL - (((l___1077[(unsigned long )((int )(o___106[0UL])->f___80) % 2UL] >> 3UL) & 15UL) | 1UL)));
    l___1088 = *((char *)(& (l___1079[1UL])->f___146) + 3);
    *((char *)(& (l___1079[1UL])->f___146) + 3) = *((char *)(& (l___1079[1UL])->f___146) + 6);
    *((char *)(& (l___1079[1UL])->f___146) + 6) = l___1088;
    l___1088 = *((char *)(& (l___1079[1UL])->f___146) + 2);
    *((char *)(& (l___1079[1UL])->f___146) + 2) = *((char *)(& (l___1079[1UL])->f___146) + 3);
    *((char *)(& (l___1079[1UL])->f___146) + 3) = l___1088;
    (o___106[(unsigned long )((int )(o___106[1UL])->f___80) % 2UL])->f___80 = l___1077[1UL];
    {
    l___1099 = 2;
    }
    break;
    case 8: 
    *(l___1075 + 0UL) = (l___1077[0UL] + l___1077[1UL]) * ((l___1079[0UL])->f___146 + (l___1079[1UL])->f___146) >> (((((o___81[0UL] + o___81[1UL]) << ((((o___106[0UL])->f___80 + (o___106[1UL])->f___80) & 7UL) | 1UL)) >> 2UL) & 7UL) | 1UL);
    {
    l___1099 = 1;
    }
    break;
    case 2: 
    l___1089 = 0U;
    l___1090 = 0U;
    {
    l___1099 = 9;
    }
    break;
    case 9: ;
    if ((unsigned long )l___1090 < 1UL) {
      {
      l___1099 = 7;
      }
    } else {
      {
      l___1099 = 8;
      }
    }
    break;
    case 5: ;
    __asm__  volatile   ("cmpl %[right], %[left]\n;\t"
                         "pushf\n;\t"
                         "popq %[tmp26]\n;\t": [tmp26] "=r" (l___1100): [left] "r" (! ((l___1077[1UL] >> 1UL) & 1UL)),
                         [right] "r" (0));
    l___1101 = ~ ((l___1100 >> 6) & 1) & 1;
    l___1102 = ~ l___1101 & 1;
    {
    l___1099 = l___1102 * 2;
    }
    break;
    case 3: 
    l___1078[0] = (struct t___145 *)0;
    l___1078[1] = (struct t___145 *)0;
    l___1079[0] = (struct t___145 *)0;
    l___1079[1] = (struct t___145 *)0;
    l___1077[0UL] = *(l___1074 + 0UL) + 395318398UL;
    l___1077[1UL] = (*(l___1074 + 0UL) * l___1077[0UL] >> 15UL) | (*(l___1074 + 0UL) * l___1077[0UL] << 49UL);
    o___81[0UL] = *(l___1074 + 0UL) | (903700589UL - l___1077[1UL]);
    o___81[1UL] = *(l___1074 + 0UL) << 1UL;
    l___1091 = malloc(24UL);
    l___1080 = (struct t___145 *)l___1091;
    l___1080->f___148 = l___1080;
    l___1080->f___147 = l___1080;
    l___1078[0UL] = l___1080;
    l___1079[0UL] = l___1080;
    l___1080->f___146 = 0UL;
    l___1092 = malloc(24UL);
    l___1081 = (struct t___145 *)l___1092;
    l___1081->f___146 = ((*(l___1074 + 0UL) + 996783958UL) << ((((l___1077[1UL] + 446531527UL) >> 1UL) & 15UL) | 1UL)) | ((*(l___1074 + 0UL) + 996783958UL) >> (64UL - ((((l___1077[1UL] + 446531527UL) >> 1UL) & 15UL) | 1UL)));
    l___1081->f___148 = (l___1079[0UL])->f___148;
    l___1081->f___147 = l___1079[0UL];
    ((l___1079[0UL])->f___148)->f___147 = l___1081;
    (l___1079[0UL])->f___148 = l___1081;
    l___1079[0UL] = (l___1079[0UL])->f___148;
    l___1093 = malloc(24UL);
    l___1082 = (struct t___145 *)l___1093;
    l___1082->f___148 = l___1082;
    l___1082->f___147 = l___1082;
    l___1078[1UL] = l___1082;
    l___1079[1UL] = l___1082;
    l___1082->f___146 = 0UL;
    l___1094 = malloc(24UL);
    l___1083 = (struct t___145 *)l___1094;
    l___1083->f___146 = (*(l___1074 + 0UL) - l___1077[0UL]) & ((l___1077[1UL] << ((((1020250812UL | o___81[0UL]) >> 4UL) & 15UL) | 1UL)) | (l___1077[1UL] >> (64UL - ((((1020250812UL | o___81[0UL]) >> 4UL) & 15UL) | 1UL))));
    l___1083->f___148 = (l___1079[1UL])->f___148;
    l___1083->f___147 = l___1079[1UL];
    ((l___1079[1UL])->f___148)->f___147 = l___1083;
    (l___1079[1UL])->f___148 = l___1083;
    l___1079[1UL] = (l___1079[1UL])->f___148;
    l___1095 = malloc(24UL);
    l___1084 = (struct t___77 *)l___1095;
    l___1084->f___78 = l___1084;
    l___1084->f___79 = l___1084;
    o___91[0UL] = l___1084;
    o___106[0UL] = l___1084;
    l___1084->f___80 = 0UL;
    l___1096 = malloc(24UL);
    l___1085 = (struct t___77 *)l___1096;
    l___1085->f___80 = (*(l___1074 + 0UL) - l___1077[1UL]) + (o___81[0UL] + o___81[1UL]);
    l___1085->f___78 = (o___106[0UL])->f___78;
    l___1085->f___79 = o___106[0UL];
    ((o___106[0UL])->f___78)->f___79 = l___1085;
    (o___106[0UL])->f___78 = l___1085;
    o___106[0UL] = (o___106[0UL])->f___78;
    l___1097 = malloc(24UL);
    l___1086 = (struct t___77 *)l___1097;
    l___1086->f___78 = l___1086;
    l___1086->f___79 = l___1086;
    o___91[1UL] = l___1086;
    o___106[1UL] = l___1086;
    l___1086->f___80 = 0UL;
    l___1098 = malloc(24UL);
    l___1087 = (struct t___77 *)l___1098;
    l___1087->f___80 = (*(l___1074 + 0UL) >> ((o___81[1UL] & 7UL) | 1UL)) - 437752715UL * (227931849UL & l___1077[1UL]);
    l___1087->f___78 = (o___106[1UL])->f___78;
    l___1087->f___79 = o___106[1UL];
    ((o___106[1UL])->f___78)->f___79 = l___1087;
    (o___106[1UL])->f___78 = l___1087;
    o___106[1UL] = (o___106[1UL])->f___78;
    {
    l___1099 = 5;
    }
    break;
    case 1: ;
    return;
    break;
    case 7: 
    o___81[1UL] = l___1077[0UL] << (((o___81[l___1090] >> 2UL) & 7UL) | 1UL);
    (l___1079[(unsigned long )l___1089 % 2UL])->f___146 = l___1077[(unsigned long )((int )(l___1079[1UL])->f___146) % 2UL];
    o___106[(unsigned long )((int )(o___106[1UL])->f___80) % 2UL] = (o___106[(unsigned long )((int )(o___106[1UL])->f___80) % 2UL])->f___78;
    l___1089 = (unsigned int )(((unsigned long )l___1089 + 1UL) % 2UL);
    l___1090 = (unsigned int )((unsigned long )l___1090 + 2UL);
    {
    l___1099 = 9;
    }
    break;
    }
  }
}
}
void o___142(void) 
{ 


  {
  return;
}
}
void o___149(void) 
{ 


  {

}
}
void o___65(void) 
{ 
  int l___1042 ;

  {
  l___1042 = 0;
  while (l___1042 < 2) {
    o___81[l___1042] = 0UL;
    l___1042 ++;
  }
}
}
void o___144(void) 
{ 


  {
  return;
}
}
void o___138(void) 
{ 


  {
  o___132();
  o___65();
  o___149();
}
}
int main(int l___1062 , char **l___1063 , char **l___1064 ) 
{ 
  unsigned long l___1066[1] ;
  unsigned long l___1067[1] ;
  int l___1068 ;
  unsigned long l___1069 ;
  int l___1070 ;

  {
  o___138();
  o___64 = l___1062;
  o___74 = l___1063;
  o___75 = l___1064;
  o___151();
  if (l___1062 != 2) {
    printf("Call this program with %i arguments\n", 1);
    exit(-1);
  }
  l___1068 = 0;
  while (l___1068 < 1) {
    l___1069 = strtoul((char const   *)*(l___1063 + (l___1068 + 1)), (char const   *)0,
                       10);
    l___1066[l___1068] = l___1069;
    l___1068 ++;
  }
  o___76((unsigned long *)(l___1066), (unsigned long *)(l___1067));
  l___1070 = 0;
  while (l___1070 < 1) {
    printf("%lu\n", l___1067[l___1070]);
    l___1070 ++;
  }
  return (0);
}
}
void o___150(void) 
{ 


  {
  return;
}
}
